require 'biblioteca/bibliografia'
require 'biblioteca/lista'
require 'biblioteca/nodo'
require 'biblioteca/version'
require 'biblioteca'
require 'biblioteca/revista'
require 'biblioteca/eleclibro'
require 'biblioteca/pra10.rb'